#!/usr/bin/env node
/*
 * http-host-proxy
 *
 * HTTP(s) proxy with host based routing to front servers, with optional SSL or authentication
 *
 * Authors: Shaggy and Dave
 *   - https://github.com/dspeed
 *   - https://github.com/shaggy-rl
 *   - https://github.com/bahamas10
 * License: MIT License
 *
 */

var fs = require('fs');
var http = require('http');
var https = require('https');
var util = require('util');

var accesslog = require('access-log');
var getopt = require('posix-getopt');
var httpProxy = require('http-proxy');
var PasshashAuth = require('passhash-auth');
var strsplit = require('strsplit');

var defaulthost = '0.0.0.0';
var defaultport = 8080;
var defaultfaildelay = 2;

var package = require('./package.json');

var opts = {
  auth: process.env.HTTPHOSTPROXY_AUTH,
  buffer: process.env.HTTPHOSTPROXY_BUFFER,
  cert: process.env.HTTPHOSTPROXY_CERT,
  faildelay: process.env.HTTPHOSTPROXY_FAIL_DELAY,
  host: process.env.HTTPHOSTPROXY_HOST,
  key: process.env.HTTPHOSTPROXY_KEY,
  port: process.env.HTTPHOSTPROXY_PORT,
  routesfile: process.env.HTTPHOSTPROXY_ROUTES,
  routes: phosts|| process.env.HTTPHOSTPROXY_ROUTES,
  ssl: process.env.HTTPHOSTPROXY_SSL,
};

//Update Checker
      require('latest').checkupdate(package, function(ret, msg) {
        console.log(msg);
        process.exit(ret);
    console.log(package.version); process.exit(0);


opts.host = opts.host || defaulthost;
opts.port = opts.port || defaultport;
opts.faildelay = typeof opts.faildelay === 'undefined' ? defaultfaildelay : opts.faildelay;

if (!routes) {
  console.error('[error] `routes` must be specified!\n\n%s',
  process.exit(1);
}

if (opts.ssl && (!opts.key || !opts.cert)) {
  console.error('[error] `key` and `cert` must be specified with `ssl=true`\n\n%s',
  process.exit(1);
}

// create the proxies
var routes = opts.routes;
var proxies = {};
Object.keys(routes).forEach(function(key) {
  var val = routes[key];
  if (typeof val === 'string') {
    var s = val.split(':');
    var host = s[0];
    var port = s[1];
    if (!port)
      port = host.indexOf('https') === 0 ? 443 : 80
    val = {
      host: host,
      port: port
    };
  }
  proxies[key] = new httpProxy.HttpProxy({target:val});
});

// create the HTTP or HTTPS server
var server;
if (opts.ssl) {
  var options = {
    key: fs.readFileSync(opts.key, 'utf8'),
    cert: fs.readFileSync(opts.cert, 'utf8')
  };
  server = https.createServer(options, onrequest);
} else {
  server = http.createServer(onrequest);
}
// server.listen(opts.port, opts.host, listening);

// create an authorization object if necessary
var auth;
if (opts.auth)
  auth = new PasshashAuth(opts.auth);

// web server started
function listening() {
  console.log('listening on %s://%s:%d',
      opts.ssl ? 'https' : 'http', opts.host, opts.port);
  if (opts.buffer) {
    // buffer the logs
    var logbuffer = require('log-buffer');
    logbuffer(8192);
    // flush every 5 seconds
    setInterval(logbuffer.flush.bind(logbuffer), 5 * 1000);
  }
}

// new web request
function onrequest(req, res) {
  // log every request with relevant information
  accesslog(req, res, function(s) {
    var prefix;
    if (opts.auth) {
      prefix = util.format('%s@%s',
          credentials && credentials.user || '<empty>',
          host || '<empty>');
    } else {
      prefix = util.format('%s',
          host || '<empty>');
    }
    console.log('[%s] %s',
      prefix, s);
  });

  var host = req.headers.host;
  var p = hasOwnProperty.call(proxies, host) ? proxies[host] : proxies['*'];
  var credentials = getcredentials(req);

  // check auth first if applicable
  if (opts.auth) {
    // don't expose auth info to the backend service if we are handling it
    delete req.headers.authorization;

    // check if credentials were given
    if (!credentials) {
      fail(res, credentials);
      return;
    }

    // check if credentials match a known user/pass
    if (!auth.checkHashMatch(credentials.user, credentials.pass)) {
      setTimeout(function() {
        fail(res, credentials);
      }, opts.faildelay * 1000);
      return;
    }
  }

  // check host header
  if (!host) {
    res.statusCode = 400;
    res.end('no host header found\n');
    return;
  }

  // check router for proxy
  if (!p) {
    res.statusCode = 404;
    res.end('no route found for host: ' + host + '\n');
    return;
  }

  // everything is set, proxy it!
  if (credentials)
    req.headers['X-Forwarded-User'] = credentials.user;
  p.proxyRequest(req, res);
}

// failed auth, send auth headers back
function fail(res, creds) {
  res.setHeader('WWW-Authenticate', 'Basic realm="Auth Required"');
  res.statusCode = 401;
  res.end();
}

// extract the credentials from the req object
function getcredentials(req) {
  var a = req.headers.authorization;
  if (!a || a.indexOf('Basic ') !== 0)
    return null;

  var ret = null;
  try {
    var s = new Buffer(a.split(' ')[1], 'base64').toString();
    var split = strsplit(s, ':', 2);
    var user = split[0];
    var pass = split[1];
    ret = {
      user: user,
      pass: pass
    };
  } catch (e) {}
  return ret;
}
